<?php
/**
 * Created by PhpStorm.
 * User: oza
 * Date: 26/03/19
 * Time: 02:46
 */

namespace OZA\Database\Tests;


use OZA\Database\Db;

class DatabaseTestCase extends TestCase
{

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        Db::fromConfig()->dropAllTables();
    }

}